on: 
  push:
    branches: dev

jobs:
  main_workflow:
    uses: DjNaGuRo/sozu/.github/workflows/cargo_doc.yml@dev
    with:
      ONLY_LIB: true
      RELEASE_MODE: true
      PROJECT_ROOT: ./cargo_toml
      